01_gen_data/rollout.sh, 04_load/rollout.sh, README.txt, tpcds.sh
Co-authored-by: Marbin Tan <tmarbin@vmware.com>
Co-authored-by: Abhijit Subramanya <subramanyaa@vmware.com>
Co-authored-by: Xin Zhang <zhxin@vmware.com>
=> GPV-736 Proper reference to dsbenchmark

README.md
Co-authored-by: Marbin Tan <tmarbin@vmware.com>
Co-authored-by: Abhijit Subramanya <subramanyaa@vmware.com>
Co-authored-by: Xin Zhang <zhxin@vmware.com>
=> GPV-737 Fix README.md font style

README.md, functions.sh, rollout.sh, tpcds.sh, tpcds_variables.sh
- Transferred user dependency from `root` to `gpadmin`
- User can login to `gpadmin` user and run TPC-DS from any location 
- Updated `README.md` with latest changes
- Removed INSTALL_DIR
- Removed creation or modification of tpcds_variables.sh by tpcds.sh
Co-authored-by: Deena Venkatesan vdeenathayal@vmware.com
Co-authored-by: Venkatram Amalanathan avenkatram@vmware.com
Co-authored-by: Stu Pollock <stuartp@vmware.com>
=> Gpv 743 remove root dependency

00_compile_tpcds/rollout.sh, 02_init/rollout.sh, 03_ddl/rollout.sh, 04_load/analyze.sh, 04_load/rollout.sh, 05_sql/rollout.sh, 06_single_user_reports/rollout.sh, 07_multi_user/rollout.sh, 07_multi_user/test.sh, 08_multi_user_reports/rollout.sh, functions.sh
- log TPC-DS tools binary versions
- log all gpdb GUCs before starting benchmark
- log gpdb version
- we didn't add time stamps in all commands just updated command which
are long running.
=> TPC-DS log time for queries and gpdb configurations

00_compile_tpcds/rollout.sh, 01_gen_data/generate_queries.sh, 01_gen_data/rollout.sh, 02_init/rollout.sh, 03_ddl/rollout.sh, 04_load/rollout.sh, 05_sql/rollout.sh, 06_single_user_reports/rollout.sh, 07_multi_user/test.sh, 09_score/rollout.sh, tpcds_tools/tpcds_cleanup.sh
- updating resource queues query to use pg_resqueue
- adding {} to variables to make them happy
- code indentation
=> GPV-720 TPC-DS script cleanup

03_ddl/rollout.sh
- Changes to the creation of the role creation for dsbench
Co-authored-by: Xin Zhang <zhxin@vmware.com>
Co-authored-by: Richard Gostanian <rgostanian@vmware.com>
=> GPV-936 update 03_ddl rollout

.github/workflows/main.yml, .travis.yml, 03_ddl/rollout.sh, 04_load/rollout.sh, Makefile, tpcds_tools/getLogResults.sh, tpcds_variables.sh
=> Gpv 889 shellcheck ci

README.md
=> Add CI status badge on README.md

tpcds_tools/validate_gbb.sh
- script checks for system and gpconfig settings
- script checks whether gcc and make packages are installed
Co-authored-by: Harshil Shah <sharshil@vmware.com>
Co-authored-by: Marbin Tan <tmarbin@vmware.com>
Co-authored-by: Xin Zhang <zhxin@vmware.com>
=> GPG-989 Create validate scipt for TPC_DS on GBB

01_gen_data/generate_data.sh, 01_gen_data/generate_queries.sh, 01_gen_data/rollout.sh, 02_init/rollout.sh, 04_load/rollout.sh, 04_load/start_gpfdist.sh, 05_sql/rollout.sh, 06_single_user_reports/rollout.sh, 07_multi_user/rollout.sh, 07_multi_user/test.sh, 08_multi_user_reports/rollout.sh, README.md, tpcds_variables.sh
- Cleaned up the awkward redirection syntax in the code and README.md
- Changed the way the activity is monitored on multi-user to prevent a
possible early exit
- Changed TABS to spaces that were missed in prior commits
- Added {} to some variables that were missed in prior commits
Co-authored-by: Brandon Tat <tatb@vmware.com>
=> GPV-902 Change redirection syntax throughout

tpcds_tools/validate_gbb.sh
- Change query for max_acting_primaries to take into account a single host
environment and prevent a divide by zero error
Co-authored-by: Wei-Ru Lin <lweiru@vmware.com>
=> GPV-989 Add check for root user execution

07_multi_user/rollout.sh, functions.sh, tpcds_tools/validate_gbb.sh
- Fix misplaced quote in 07_multiuser/rollout.sh
- Fixed undeclared variable in functions.sh
=> Gpv 1130 fix errors

07_multi_user/test.sh
Co-authored-by: Jianwen Dong <djianwen@vmware.com>
=> GPV-902 Removed -p from psql command in test.sh in 07_multi_user

Makefile
Co-authored-by: Jianwen Dong <djianwen@vmware.com>
Co-authored-by: Wei-Ru Lin <lweiru@vmware.com>
=> GPV-903 add -sr to shfmt in the Makefile

01_gen_data/generate_queries.sh, 01_gen_data/rollout.sh, 02_init/rollout.sh, 04_load/analyze.sh, 04_load/start_gpfdist.sh, 05_sql/rollout.sh, 07_multi_user/rollout.sh, 07_multi_user/test.sh, functions.sh, tpcds_tools/getLogResults.sh, tpcds_tools/validate_gbb.sh
Co-authored-by: Jianwen Dong <djianwen@vmware.com>
=> GPV-903 apply suggestions from shfmt

01_gen_data/rollout.sh, 03_ddl/rollout.sh, 04_load/rollout.sh, functions.sh
- update version function to scan for gpdb7
- update rollout scripts to support gpdb_7 string from version function
Authored-by: Gaurab Dey <gaurabd@vmware.com>
=> GPV-1363: Support gpdb7

01_gen_data/rollout.sh, 02_init/rollout.sh, 03_ddl/rollout.sh, 04_load/analyze.sh, 04_load/rollout.sh, 05_sql/rollout.sh, 06_single_user_reports/rollout.sh, 07_multi_user/test.sh, 08_multi_user_reports/rollout.sh, 09_score/rollout.sh, functions.sh, tpcds_tools/tpcds_get_gucs.sh, tpcds_tools/tpcds_set_gucs.sh, tpcds_tools/validate_gbb.sh, tpcds_variables.sh
- This reverts commit 4327a8d59a767031d573a062eea2343d10539b59.
- Remove usage of `PSQL_OPTIONS`
=> Revert "GPV-1364: Update psql to use PSQL_OPTIONS"

README.md
Co-authored-by: Marbin Tan <tmarbin@vmware.com>
Co-authored-by: Brandon Tat <tatb@vmware.com>
=> GPV-1364 Update README.md to include libpq env vars

04_load/rollout.sh
The current query references pg_partitions which no longer exists.  Replace that query with a gpdb7 equivalent.
=> Fix gpdb7 root partition query

07_multi_user/rollout.sh, functions.sh, tpcds.sh, tpcds_variables.sh
- replace hardcoded usage of TPC-DS directory name with variable
Authored-by: Gaurab Dey <gaurabd@vmware.com>
=> GPV-1306: Fix usage of default directory name

00_compile_tpcds/rollout.sh, 01_gen_data/rollout.sh, 02_init/rollout.sh, 04_load/rollout.sh, tpcds_tools/tpcds_cleanup.sh, tpcds_variables.sh
=> GPV-1714 fix banner output

functions.sh
- refactored compression setting logic to use best option available independent of the version
- refactored get_pwd to handle relative and absolute paths
=> GPV-1733 Added check for zstd support utilized in gpdb7

01_gen_data/generate_data.sh, 01_gen_data/generate_queries.sh, 01_gen_data/rollout.sh, 07_multi_user/rollout.sh, README.md, functions.sh, tpcds_variables.sh
We can control the RNGSEED to generate data and queries. If we want to change the distribution and query predicates, we can just change the RNGSEED.
Authored-by: Xin Zhang <zhxin@vmware.com>
=> GPV-1842 Add RNGSEED support

tpcds_tools/validate_gbb.sh
- allow to run without default gpadmin user
=> Replace hardcoded `gpadmin` with ADMIN_USER var

09_score/rollout.sh
Error when running `tpcds.sh` with `RUN_SQL="true"` and setting other vars to false `RUN_XX="false"`:
```
Finished single_user_reports
Skip /path/TPC-DS/07_multi_user/rollout.sh
Skip /path/TPC-DS/08_multi_user_reports/rollout.sh
Run /path/TPC-DS/09_score/rollout.sh
ERROR:  relation "tpcds_testing.sql" does not exist
LINE 1: ...t round(sum(extract('epoch' from duration))) from tpcds_test...
```
We fixed the error in this commit.
=> fix error: relation 'tpcds_testing.sql' does not exist when only running sql
